name: myparkingapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  form_field_validator: ^1.1.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  fl_chart: ^0.70.2
  flutter_localization: ^0.3.1
  get: ^4.6.6
  flutter_bloc: ^9.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  http: ^1.3.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  loading_animation_widget: ^1.3.0
  geolocator: ^13.0.3
  flutter_markdown: ^0.7.6+2
  google_generative_ai: ^0.4.6
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  vnpay_flutter: ^1.0.3
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.10.0
  image_picker_web: ^4.0.0
  cloudinary: ^1.2.0
  flutter_dotenv: ^5.2.1
  qr_flutter: ^4.1.0
  crypto: ^3.0.6
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logoApp.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true # Bật tính năng tự động generate file dịch
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/Illustrations/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/vi.json
    - assets/images/image_card_credit/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

